DB_USER: postgres
DB_PASSWORD: 123
DB_NAME: munu
DB_HOST: localhost
DB_PORT: 5432
DB_SSLMODE: "disable"
CORS_ORIGINS: "*"
JWT_SECRET: secret
ADDRESS_PUBLIC: "https://localhost:4430"
OAUTH_GOOGLE_KEY: 123.example.googleusercontent.com
OAUTH_GOOGLE_SECRET: google123
OAUTH_GOOGLE_CALLBACK_URL: http://localhost:8089/api/auth/flow/google/callback
OAUTH_SESSION_SECRET: secret
OAUTH_REDIRECT_URL: https://localhost:4430/auth/login
MAIL_USERNAME: your_email@example.com.br
MAIL_PASSWORD: "123"
MAIL_FROM: your_email@example.com.br
MAIL_SMTP_HOST: host.com
MAIL_SMTP_PORT: 587
