DB_USER: postgres
DB_PASSWORD: 123
DB_NAME: munu
DB_HOST: localhost
DB_PORT: 5432
CORS_ORIGINS: "*"
JWT_SECRET: secret
CEP_ABERTO_API_TOKEN: 123
PAGARME_API_KEY: sk_test_7GqQo2Un8Sa69YEn
OWN_PUBLIC_URL: "http://localhost:8089"
ADDRESS_PUBLIC: "https://localhost:4430"
OAUTH_SESSION_SECRET: secret
OAUTH_REDIRECT_URL: https://localhost:4430/auth/login
MAIL_USERNAME: seuemail@falqon.com.br
MAIL_PASSWORD: 123
MAIL_FROM: seuemail@falqon.com.br
MAIL_SMTP_HOST: smtp-relay.sendinblue.com
MAIL_SMTP_PORT: 587
